### ISSUE TITLE
💡Option to choose storage configuration in automated order

### ISSUE THREAD

**Issue by zercad** [TheoBrigitte/kimsufi-notifier#13]
Hello, 
maybe it is already among the things you plan to implement, but if not, how about adding the option to choose preferred storage configuration when setting up an automated order?

Regards

**Comment by zercad** [comment]
Well from what i can see you are at least indeed the owner of the bot I am using XD
So i will reopen it, feel free to close it again it it does not apply to this repo.

**Comment by TheoBrigitte** [comment]
The bot now offers the possibility to choose storage and memory options in automated order. Closing here.
